
package mypackage;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchUserException", targetNamespace = "http://controllers/")
public class NoSuchUserException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonWebServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchUserException(String message, PersonWebServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoSuchUserException(String message, PersonWebServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mypackage.PersonWebServiceFault
     */
    public PersonWebServiceFault getFaultInfo() {
        return faultInfo;
    }

}
